name: PR commenter
on: push
jobs:
  platform-bot:
    runs-on: ubuntu-latest
    name: platform-bot label check
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 
        id: checker
        uses: aidan-ogorman-dev/hello-world-action@v2
        env:
          REPO_FILES: ${{ steps.abc.outputs.all }}
      - name: Commit changes
        run: |
          pwd
          ls -lrth
          echo ${{ github.workspace }}
          ls -lrth ${{ github.workspace }}
          git config --global user.name 'platform-bot'
          git config --global user.email 'platform-bot@users.noreply.github.com'
          git commit -am ":robot: platform-bot CI :robot:]"
          git push
