name: PR commenter
on: push
jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 
        id: checker
        uses: aidan-ogorman-dev/hello-world-action@v2
        env:
          REPO_FILES: ${{ steps.abc.outputs.all }}
      - name: Commit changes
        run: |
          git config --global user.name 'platform-bot'
          git config --global user.email 'platform-bot@users.noreply.github.com'
          git commit -am "Ensuring required labels"
          git push
