name: PR commenter
on: push
jobs:
  platform-bot:
    runs-on: ubuntu-latest
    name: platformBot label checker
    steps:
      - uses: actions/checkout@v3
      - uses: jitterbit/get-changed-files@v1
        id: changed_files
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: 
        id: label_checker
        uses: aidan-ogorman-dev/platform-label-checker@v1
        env:
          REPO_FILES: ${{ steps.changed_files.outputs.added_modified }}
      - name: Commit changes
        run: |
          git config --global user.name 'platform-bot'
          git config --global user.email 'platform-bot@users.noreply.github.com'
          git commit -am ":robot: platform-bot CI :robot:"
          git push
